#ifndef strandtest_h
#define strandtest_h

typedef enum {
	NO_BUTTON_PRESSED,
	M_BUTTON_PRESSED,
	E_BUTTON_PRESSED,
	ME_BUTTON_PRESSED,
	M_BUTTON_PRESSED_SHORT,
	E_BUTTON_PRESSED_SHORT,
	ME_BUTTON_PRESSED_SHORT,
	M_BUTTON_PRESSED_LONG,
	E_BUTTON_PRESSED_LONG,
	ME_BUTTON_PRESSED_LONG,
} button_status_t;

#endif
